### ISSUE TITLE
torn reads/writes during optimistic handling phase

### ISSUE THREAD

**Issue by usergoodvery** [LPD-EPFL/ASCYLIB#17]
Hi,
I have looked through some of the examples included in the library specifically the hashtable, as I am looking to replace traditional mutex based locking in my own hashtable implementation, which resizes dynamically and uses open addressing for collision resolution, with optik lock. It seems to me there is more to it than the simple  semantics of  version lookup, validation, etc... It seems I have to now convert some of my variables into atomic types in order to avoid torn reads/writes. For example, inserting new  element I'd need to check the current size of the table, reading off the value without the safetynet of a mutex or atomic load can result in torn read. How do you deal with that under the optik pattern?
I was hoping to be able to resize optimistically, and apply the lock only when i am ready to rehash items, because that's an expensive operation to have to restart upon version pdates, but if my snapshot of the original size is torn, that is an issue, to state it mildly. I could very well be missing something totally basic, though.

regards

**Comment by trigonak** [comment]
Hi,

Sorry for the late answer.

The memory consistency requirements of OPTIK are mentioned in the corresponding paper (Optimistic Concurrency with OPTIK). Read also the "OPTIK and Memory Fences" subsection. Due to the memory consistency model of x86 processors, when you read the OPTIK value with `optik get version` you don't need any memory fences. 

Does this answer your question? 
If not, it's probably better if you show me a code snippet of what you are modifying.

**Comment by usergoodvery** [comment]
Hi thanks. I think I am clear on how OPTIK "mechanically" functions, including underlying memory model. What I am garbling with  is more generalise in nature. Considering a typical expandable hashtable semantic where a new item is being added:

Under traditional locking I'd be doing:
------------------------------
lock_hashtable();
if (hashtable->current_size==MAX)
{
 //expensive operation, because all items have to be rehashed relative to new table size, causing the lock to be held for longer
 ExpandHashTable();
}
AddItemToHash();  //hashtable->current_size++
unlock_hashtable();
----------------------------

In the above, hashtable->current_size will always be consistent because it is read under lock.

Applying the OPTIK locking pattern, I reasoned I'd rather resize optimistically and without acquiring lock, until the table has been resized and all elements rebased. However, I have to test for the size of the table first, and I'd be doing that without a lock on the table, but then other thread could be in the middle of updating the hashtable->current_size variable. If I convert that to atomic type, then that's no issue. However, applying this to other data types would involve considerable change.

In your examples you don't seem to be particularly  concerned with that general issue, and none of your basic types are atomic (for example list size), which made me think I could be missing something very fundamental, or my understanding is flawed somehow.

regards,

ayman

**Comment by trigonak** [comment]
Aha, I see now. From what I understand, changing the `current_size` variable to atomic will not make a difference in your case (because there is still only one thread the can write to this variable -- meaning that you don't need a store with an atomic operation). 

However, I can see an important problem with re-balancing the hash table outside of the lock. Since the re-balancing does not synchronize, other threads are allowed to insert and delete elements while the re-balancing is ongoing. In that case, the re-balancing thread could miss these other updates...

**Comment by usergoodvery** [comment]
I think converting current_size to native atomic would help, because that will always get a full read (where it reads it from is another matter: relaxed vs seq_consistent  etc...) otherwise theoretically I'd be risking a torn read, even if one thread is doing that, but that assumption about the number of threads is not relevant here.  That's what prompted me to open this issue in the first instance.

As I alluded before, generally in the OPTIK literature you seem to be reading non-atomic variants liberally during  "optimistic work" phase. 

Regarding second point if the number of elements was read correctly after applying  optik get version () that will give me a snapshot of the number of elements which may or may not change later further down the track. Then in theory, as I am ready to commit my new table, if optik trylock version (...) fails that tells me other threads have successfully added/removed , so I try again etc... because the only way  number of elements would change if another thread succeeded in acquiring the lock and committed its own changes.

**Comment by trigonak** [comment]
Regarding the first point: Atomicity and memory consistency are somehow two different things. Reading and writing 8 (aligned) bytes is always atomic in hardware: It always reads/writes the full 8 bytes atomically (see [atomic registers](http://stackoverflow.com/questions/8871633/whats-the-difference-between-safe-regular-and-atomic-registers) -- hardware always provides "atomic registers"). Doing a `variable++` operation is *not atomic*, thus it must be protected by a lock if there might be multiple concurrent `++` on the same memory location. However, a concurrent read to a `variable++` operation is atomic -- it either reads the value before or after the `++`, which is  essentially equivalent to `atomic_inc()`, as concurrent readers either read before or after the `atomic_inc`. 

Therefore, since atomicity of reads/writes is not really an issue, the problems that might arise are due to memory consistency. In other words, as you mentioned in your previous comments, the hardware or the compiler might reorder some memory operations. With OPTIK, hardware reordering is not an issue due to the x86 memory model (you can find a very nice video regarding the topic [here](https://www.youtube.com/watch?v=WUfvvFD5tAA) -- watch the locking example at 24:37). To make sure that the compiler is not going to reorder things, you need (in C) to use `volatile` variables and compiler barriers ([more info](http://www.oracle.com/technetwork/server-storage/solarisstudio/documentation/oss-compiler-barriers-176055.pdf)).

Regarding the second point, your algorithm seems correct indeed :-). I hadn't understood the exact modifications that you had in mind.

**Comment by usergoodvery** [comment]
I think I am a bit on the pedantic side of things and definitely the core of my  enquiry relates to atomicity and not memory ordering issues (hence the title of the issue). 
It is plausible to consider reads/writes on modern x84 as atomic, but that 'guarantee' doesn't hold  universally on other systems. For a 64bit value compiler could possibly issue two instructions using DWORD, one to read the lower 32 bits into some register, and another read for the upper 32 bits into another. In fact on x84 my understanding that may happen under situations where unaligned access crosses a cache line boundary or  even a page boundary.

I don't think there is an issue per se with OPTIK's implementation--it's a clever  approach, it is just the pattern of combining optimistic handling with locking may produce unintended results if one is not aware of potential atomicity issues relating to reading non-atomic variables during optimistic handling phase. As you stressed earlier, this is distinct from ordering.

Thanks for confirming the other point around the steps for expanding the hashtable.

**Comment by trigonak** [comment]
Yes, indeed, unaligned accesses could be an atomicity problem.
From [Intel 64 and IA-32 Architectures Software Developer’s Manual Volume 3A: Section 8.1](http://download.intel.com/design/processor/manuals/253668.pdf):
> These mechanisms are interdependent in the following ways. Certain basic memory
transactions (such as reading or writing a byte in system memory) are always guaranteed
to be handled atomically.
 
They talk about guaranteed atomicity at byte granularity.

Thanks for pointing out this issue.
